language: cpp
dist: trusty

before_install:
  # C++14
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  # C++14
  - sudo apt-get install -qq g++-6 cmake
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90

script: mkdir build && cd build && cmake -DPASTICCIOTTO_DEBUG=On .. && make && ./bin/pasticciotto-tests